### PR TITLE
README.md: Tweak English

### PR DESCRIPTION
**Pull request by msabramo**

### CODE REVIEW

**Comment by rarylson** [comment]
Hi, @msabramo.

At first, thank you for your help and for contributing in the Open Source community.

Soon, I will merge your patch into the master and develop branches (and update the description in PyPI).

I swear I'm studing and improving my English day by day :). But sometimes I make some mistakes.

I saw you prefer the term "snippets" to the term "splitted files". I have thought about this change. "snippets" is a cleaner term, and it seems people prefer it.

So, after merging your code, I'll update the source code (develop branch) to reflect the choise of "snippets" over "splitted files".

**Comment by msabramo** [comment]
Yeah, the reason I changed it to "snippets" is because I don't know if "splitted" is a word. Even if it is, it sounds strange to my ears.

Don't worry too much about your English. Just do your best and other folks like me can help tighten stuff up here and there. That will improve the project and you can learn a bit while you're at it.

Thanks for sharing your project!

**Comment by rarylson** [comment]
Hi @msabramo.

At first, thanks for your feedback.

I updated the code to use the term "snippets". I think it's better (as you proposed in your pull request when updating the docs).

The changes were applied in the [develop branch](https://github.com/rarylson/update-conf.py/tree/develop), in this [commit](https://github.com/rarylson/update-conf.py/commit/98fe0e8718fad07ef206aac494ab832f9f36883b).

Could you check the commit? I would really apreciate your opinion.

Thanks in advance.

**Comment by msabramo** [comment]
Looks great!

The word "split" is confusing, because the past tense is the same - "split". 

http://www.answers.com/Q/What_is_the_past_tense_of_split

It's a bug in English! :)

I'll tend to go for something else like divided, partitioned, chopped, etc. because those have a different past tense so less confusing.

**Pull request merged**
